Profile page
Molnes/Nyhetsjeger pull request #92
Opened 2024-03-30 16:26 UTC by Oransj

2024-03-30 17:17 UTC, z-rayc requested changes
- Horizontally center tooltip relative to button
- Fix responsive width of profile page
- Update style to look a bit more like the main quiz page (i.e. remove purple color, maybe add a bit more spacing between elements).
- Why is there terms of service on profile page? Remove

2024-03-30 17:38 UTC, Molnes requested changes

2024-03-30 17:38 UTC, Molnes commented on package-lock.json
remove changes to this

2024-03-30 17:38 UTC, Molnes commented on package.json
> +}
remove changes to these aswell

2024-03-30 18:00 UTC, Oransj commented on package.json
> +}
done

2024-03-30 18:14 UTC, Molnes commented on package.json
> +}
fixed it for you

2024-03-31 17:27 UTC, z-rayc approved these changes

2024-03-31 17:30 UTC, merged